// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagmen.Server.Data;

#nullable disable

namespace OrderManagmen.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220425112948_Statuses")]
    partial class Statuses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrderManagmen.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://envybox.io/blog/wp-content/uploads/2020/10/10.jpg",
                            Note = "Небольшой заказ",
                            Number = "1",
                            Price = 9.99m,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://personalufa.ru/upload/iblock/dd1/dd18d2b8b4b413c1845ab8f3de679710.jpg",
                            Note = "Средний заказ",
                            Number = "2",
                            Price = 19.99m,
                            StatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://cdn.the-village.ru/the-village.ru/post_image-image/2XxOa2gwgzh8kEzt0esBtw-wide.jpg",
                            Note = "Большой заказ",
                            Number = "3",
                            Price = 29.99m,
                            StatusId = 2
                        });
                });

            modelBuilder.Entity("OrderManagmen.Shared.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending",
                            Url = "pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Completed",
                            Url = "completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cancelled",
                            Url = "cancelled"
                        });
                });

            modelBuilder.Entity("OrderManagmen.Shared.Order", b =>
                {
                    b.HasOne("OrderManagmen.Shared.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
